// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function AdjustStock(arg1:number,arg2:number):Promise<void>;

export function CreateCategory(arg1:string):Promise<number>;

export function CreateItem(arg1:string,arg2:number,arg3:string):Promise<number>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteItem(arg1:number):Promise<void>;

export function GetCategories():Promise<Array<service.CategoryDTO>>;

export function GetCheckoutCategories():Promise<Array<service.CategoryWithItemsDTO>>;

export function GetItems():Promise<Array<service.ItemWithStockDTO>>;

export function GetItemsByCategory(arg1:number):Promise<Array<service.ItemWithStockDTO>>;

export function GetLowStockItems(arg1:number):Promise<Array<service.ItemWithStockDTO>>;

export function GetOrdersHistory():Promise<Array<service.OrderHistoryDTO>>;

export function GetStock(arg1:number):Promise<service.StockDTO>;

export function InsertOrder(arg1:number,arg2:number,arg3:number):Promise<void>;

export function SaveReceipt(arg1:string):Promise<void>;

export function SetStock(arg1:number,arg2:number):Promise<void>;

export function UpdateCategory(arg1:number,arg2:string):Promise<void>;

export function UpdateItem(arg1:number,arg2:string,arg3:number,arg4:string):Promise<void>;
