// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCheckoutCategories() {
  return window['go']['main']['App']['GetCheckoutCategories']();
}

export function GetOrdersHistory() {
  return window['go']['main']['App']['GetOrdersHistory']();
}

export function InsertOrder(arg1, arg2, arg3) {
  return window['go']['main']['App']['InsertOrder'](arg1, arg2, arg3);
}

export function SaveReceipt(arg1) {
  return window['go']['main']['App']['SaveReceipt'](arg1);
}
