// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function GetCheckoutCategories():Promise<Array<service.CategoryWithItemsDTO>>;

export function GetOrdersHistory():Promise<Array<service.OrderHistoryDTO>>;

export function InsertOrder(arg1:number,arg2:number,arg3:number):Promise<void>;

export function SaveReceipt(arg1:string):Promise<void>;
