// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function GetCheckoutCategories():Promise<Array<service.CategoryWithItemsDTO>>;
