// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdjustStock(arg1, arg2) {
  return window['go']['main']['App']['AdjustStock'](arg1, arg2);
}

export function CreateCategory(arg1) {
  return window['go']['main']['App']['CreateCategory'](arg1);
}

export function CreateItem(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateItem'](arg1, arg2, arg3);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteItem(arg1) {
  return window['go']['main']['App']['DeleteItem'](arg1);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetCheckoutCategories() {
  return window['go']['main']['App']['GetCheckoutCategories']();
}

export function GetItems() {
  return window['go']['main']['App']['GetItems']();
}

export function GetItemsByCategory(arg1) {
  return window['go']['main']['App']['GetItemsByCategory'](arg1);
}

export function GetLowStockItems(arg1) {
  return window['go']['main']['App']['GetLowStockItems'](arg1);
}

export function GetOrdersHistory() {
  return window['go']['main']['App']['GetOrdersHistory']();
}

export function GetStock(arg1) {
  return window['go']['main']['App']['GetStock'](arg1);
}

export function InsertOrder(arg1, arg2, arg3) {
  return window['go']['main']['App']['InsertOrder'](arg1, arg2, arg3);
}

export function SaveReceipt(arg1) {
  return window['go']['main']['App']['SaveReceipt'](arg1);
}

export function SetStock(arg1, arg2) {
  return window['go']['main']['App']['SetStock'](arg1, arg2);
}

export function UpdateCategory(arg1, arg2) {
  return window['go']['main']['App']['UpdateCategory'](arg1, arg2);
}

export function UpdateItem(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateItem'](arg1, arg2, arg3, arg4);
}
